# Web Scraping – Flipkart ExplorePlus Smartwatch Data  

## Objective  
Collect smartwatch product data from Flipkart ExplorePlus listings using web scraping techniques for further analysis and market insights.

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import requests
import warnings
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup

## Data Extraction Strategy  

- Scraped 100 pages of smartwatch listings.  
- Extracted key attributes including product name, price, original price, discount, ratings, reviews, sponsorship status, and promotional tags.  
- Used BeautifulSoup for HTML parsing and Requests for page retrieval.  
- Captured page number for tracking pagination.

In [13]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

Sponsored = [] 
Productname = []
Colour=[]
Fassured = []
Price = []
Original_price = []
Discount = []
Promotion_tag=[]
Ratings=[]
Reviews=[]
pagenum = []


total_time = time.time()

for i in range(1,101): 
    start_time = time.time()
    URL = f"https://www.flipkart.com/search?q=smart+wearable&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&otracker=nmenu_sub_Electronics_0_Smart+Wearable+Tech&page={i}"
    page = requests.get(URL)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', attrs={'class':'RGLWAk'}):
        span = x.find('div', attrs={'class':'IxWX8O'})
        prod = x.find('a', attrs={'class':'pIpigb'})   
        colo= x.find('div', attrs={'class':'U_GKRr'})
        fass = x.find('div', attrs={'class':'FIdGa1'})
        pr = x.find('div', attrs={'class':'hZ3P6w'})
        op = x.find('div', attrs={'class':'kRYCnD'})
        discount = x.find('div', attrs={'class':'HQe8jr'})
        Promo= x.find('div', attrs={'class':'MaiFhH'})
        ratings= x.find('div', attrs={'class':'MKiFS6'})
        reviews= x.find('span', attrs={'class':'PvbNMB'})
        

        Sponsored.append( True if  span else False)
        Productname.append(prod.text if prod else np.nan)
        Colour.append(colo.text if colo else np.nan)
        Fassured.append(True if fass else False)
        Price.append(pr.text if pr else np.nan)
        Original_price.append(op.text if op else np.nan)
        Discount.append(discount.text if discount else np.nan)
        Promotion_tag.append( Promo.text if  Promo else np.nan)
        Ratings.append(ratings.text if ratings else np.nan)
        Reviews.append( reviews.text if  reviews else np.nan)

        pagenum.append(i)
    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 0.87 seconds
Page 2 completed in 1.02 seconds
Page 3 completed in 1.51 seconds
Page 4 completed in 1.37 seconds
Page 5 completed in 0.82 seconds
Page 6 completed in 1.61 seconds
Page 7 completed in 2.01 seconds
Page 8 completed in 0.61 seconds
Page 9 completed in 0.71 seconds
Page 10 completed in 0.59 seconds
Page 11 completed in 1.86 seconds
Page 12 completed in 1.30 seconds
Page 13 completed in 1.23 seconds
Page 14 completed in 2.40 seconds
Page 15 completed in 1.83 seconds
Page 16 completed in 1.32 seconds
Page 17 completed in 2.39 seconds
Page 18 completed in 1.77 seconds
Page 19 completed in 1.71 seconds
Page 20 completed in 1.58 seconds
Page 21 completed in 4.48 seconds
Page 22 completed in 1.47 seconds
Page 23 completed in 1.32 seconds
Page 24 completed in 1.08 seconds
Page 25 completed in 0.76 seconds
Page 26 completed in 0.60 seconds
Page 27 completed in 0.35 seconds
Page 28 completed in 0.43 seconds
Page 29 completed in 0.10 seconds
Page 30 completed in 0.56 seconds
Page 31 completed in 0.38 seconds
Page 32 completed in 0.33 seconds
Page 33 completed in 0.41 seconds
Page 34 completed in 0.48 seconds
Page 35 completed in 0.71 seconds
Page 36 completed in 0.82 seconds
Page 37 completed in 0.42 seconds
Page 38 completed in 0.45 seconds
Page 39 completed in 0.53 seconds
Page 40 completed in 0.37 seconds
Page 41 completed in 0.40 seconds
Page 42 completed in 0.35 seconds
Page 43 completed in 0.31 seconds
Page 44 completed in 0.31 seconds
Page 45 completed in 0.41 seconds
Page 46 completed in 0.47 seconds
Page 47 completed in 0.41 seconds
Page 48 completed in 0.49 seconds
Page 49 completed in 0.63 seconds
Page 50 completed in 0.33 seconds
Page 51 completed in 0.36 seconds
Page 52 completed in 0.32 seconds
Page 53 completed in 0.29 seconds
Page 54 completed in 0.25 seconds
Page 55 completed in 0.30 seconds
Page 56 completed in 0.57 seconds
Page 57 completed in 0.76 seconds
Page 58 completed in 0.29 seconds
Page 59 completed in 0.26 seconds
Page 60 completed in 0.57 seconds
Page 61 completed in 0.66 seconds
Page 62 completed in 0.43 seconds
Page 63 completed in 0.31 seconds
Page 64 completed in 0.24 seconds
Page 65 completed in 0.57 seconds
Page 66 completed in 0.61 seconds
Page 67 completed in 0.28 seconds
Page 68 completed in 0.33 seconds
Page 69 completed in 0.48 seconds
Page 70 completed in 0.46 seconds
Page 71 completed in 0.33 seconds
Page 72 completed in 0.35 seconds
Page 73 completed in 0.27 seconds
Page 74 completed in 0.28 seconds
Page 75 completed in 0.55 seconds
Page 76 completed in 0.37 seconds
Page 77 completed in 0.51 seconds
Page 78 completed in 0.29 seconds
Page 79 completed in 0.57 seconds
Page 80 completed in 0.61 seconds
Page 81 completed in 0.85 seconds
Page 82 completed in 1.35 seconds
Page 83 completed in 0.34 seconds
Page 84 completed in 0.75 seconds
Page 85 completed in 0.32 seconds
Page 86 completed in 0.57 seconds
Page 87 completed in 0.56 seconds
Page 88 completed in 1.08 seconds
Page 89 completed in 0.38 seconds
Page 90 completed in 0.37 seconds
Page 91 completed in 0.42 seconds
Page 92 completed in 0.39 seconds
Page 93 completed in 0.34 seconds
Page 94 completed in 0.35 seconds
Page 95 completed in 0.48 seconds
Page 96 completed in 1.64 seconds
Page 97 completed in 0.59 seconds
Page 98 completed in 0.36 seconds
Page 99 completed in 0.38 seconds
Page 100 completed in 0.67 seconds
Total Time Completed in seconds 73.33607006072998

## Scraping Performance Summary  

- Successfully scraped 100 pages.  
- Total execution time: ~73 seconds.  
- Generated 1000 smartwatch records.

In [14]:
df=pd.DataFrame({"Productname":Productname,
                 "Colour":Colour,
                 "Flipkart_assured":Fassured,
                 "Sponsored":Sponsored,
                 "Price":Price,
                 "Original_price":Original_price,
                 "Discount":Discount,
                 "Promotion_tag":Promotion_tag,
                 "Page_num" : pagenum,
                 "Ratings":Ratings,
                 "Reviews":Reviews})

#  Data Cleaning & Transformation  

Convert raw scraped data into structured and analysis-ready format.

In [15]:
df

,Productname,Colour,Flipkart_assured,Sponsored,Price,Original_price,Discount,Promotion_tag,Page_num,Ratings,Reviews
0,"boAt Wave Fury with 1.83'' HD Display, Bluetoo...","Blue Strap, Free Size",True,True,"₹1,099","₹6,999",84% off,Super Deals,1,4.1,"(1,35,086)"
1,Noise Colorfit Icon 2 1.8'' Display with Bluet...,"Midnight Blue Strap, Regular",True,True,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
2,Noise Icon 2 1.8'' Display with Bluetooth Call...,"Rose Pink Strap, Regular",True,False,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
3,"boAt Wave Fury with 1.83'' HD Display, Bluetoo...","Active Black Strap, Free Size",True,False,"₹1,099","₹6,999",84% off,Super Deals,1,4.1,"(1,35,086)"
4,Noise Colorfit Icon 2 1.8'' Display with Bluet...,"Jet Black Strap, Regular",True,False,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
...,...,...,...,...,...,...,...,...,...,...,...
995,"GOBOULT Drift Max 2.01''HD Screen, BT Calling,...","Pure Black Strap, Free Size",True,False,"₹1,299","₹7,999",83% off,Upto ₹300 Off on Exchange,25,4.1,"(8,713)"
996,Fire-Boltt Talk 35.3mm (1.39) Bluetooth Callin...,"Milange Grey Strap, 46",True,True,"₹1,299","₹9,999",87% off,Upto ₹300 Off on Exchange,25,4.1,"(3,35,485)"
997,GameSir T500 Pink-A1 Full Screen Touch Watch S...,"Pink Strap, ""Free Size Elegant Women's Smartwa...",True,True,₹695,"₹1,999",65% off,Bank Offer,25,3.7,(218)
998,Fire-Boltt Astra Luxury Stainless Steel Smart ...,"Gold Black Strap, Free Size",True,False,"₹2,799","₹21,000",86% off,Upto ₹300 Off on Exchange,25,4.1,"(41,025)"
999,Yash Enterprises PulseWave Smart Band Watch T5...,"BLACK Strap, FREE SIZE",False,False,₹463,"₹2,113",78% off,Bank Offer,25,3.5,"(17,292)"

In [16]:
df.isnull().sum()

Productname          0
Colour               0
Flipkart_assured     0
Sponsored            0
Price                6
Original_price      19
Discount            19
Promotion_tag        6
Page_num             0
Ratings             60
Reviews             60
dtype: int64

In [17]:
df.duplicated().sum()

0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Productname       1000 non-null   object
 1   Colour            1000 non-null   object
 2   Flipkart_assured  1000 non-null   bool
 3   Sponsored         1000 non-null   bool
 4   Price             994 non-null    object
 5   Original_price    981 non-null    object
 6   Discount          981 non-null    object
 7   Promotion_tag     994 non-null    object
 8   Page_num          1000 non-null   int64
 9   Ratings           940 non-null    object
 10  Reviews           940 non-null    object
dtypes: bool(2), int64(1), object(8)
memory usage: 72.4+ KB

In [20]:
df.to_csv("Webscraping_Flipkart.csv", index = True)

In [21]:
df

,Productname,Colour,Flipkart_assured,Sponsored,Price,Original_price,Discount,Promotion_tag,Page_num,Ratings,Reviews
0,"boAt Wave Fury with 1.83'' HD Display, Bluetoo...","Blue Strap, Free Size",True,True,"₹1,099","₹6,999",84% off,Super Deals,1,4.1,"(1,35,086)"
1,Noise Colorfit Icon 2 1.8'' Display with Bluet...,"Midnight Blue Strap, Regular",True,True,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
2,Noise Icon 2 1.8'' Display with Bluetooth Call...,"Rose Pink Strap, Regular",True,False,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
3,"boAt Wave Fury with 1.83'' HD Display, Bluetoo...","Active Black Strap, Free Size",True,False,"₹1,099","₹6,999",84% off,Super Deals,1,4.1,"(1,35,086)"
4,Noise Colorfit Icon 2 1.8'' Display with Bluet...,"Jet Black Strap, Regular",True,False,₹999,"₹5,999",83% off,Super Deals,1,4.1,"(8,83,543)"
...,...,...,...,...,...,...,...,...,...,...,...
995,"GOBOULT Drift Max 2.01''HD Screen, BT Calling,...","Pure Black Strap, Free Size",True,False,"₹1,299","₹7,999",83% off,Upto ₹300 Off on Exchange,25,4.1,"(8,713)"
996,Fire-Boltt Talk 35.3mm (1.39) Bluetooth Callin...,"Milange Grey Strap, 46",True,True,"₹1,299","₹9,999",87% off,Upto ₹300 Off on Exchange,25,4.1,"(3,35,485)"
997,GameSir T500 Pink-A1 Full Screen Touch Watch S...,"Pink Strap, ""Free Size Elegant Women's Smartwa...",True,True,₹695,"₹1,999",65% off,Bank Offer,25,3.7,(218)
998,Fire-Boltt Astra Luxury Stainless Steel Smart ...,"Gold Black Strap, Free Size",True,False,"₹2,799","₹21,000",86% off,Upto ₹300 Off on Exchange,25,4.1,"(41,025)"
999,Yash Enterprises PulseWave Smart Band Watch T5...,"BLACK Strap, FREE SIZE",False,False,₹463,"₹2,113",78% off,Bank Offer,25,3.5,"(17,292)"